module.exports = {
  preset: "jest-expo",
  silent: true,
  setupFiles: ["<rootDir>/jest.setup.ts"],
  moduleNameMapper: {
    "^@/src/(.*)$": "<rootDir>/src/$1",
    "^@/core/(.*)$": "<rootDir>/src/core/$1",
    "^@/shared/(.*)$": "<rootDir>/src/shared/$1",
    "^@/layout/(.*)$": "<rootDir>/src/layout/$1",
    "^@/auth/(.*)$": "<rootDir>/src/auth/$1",
    "^@/feed/(.*)$": "<rootDir>/src/feed/$1",
    "^@/chat/(.*)$": "<rootDir>/src/chat/$1",
    "^@/explore/(.*)$": "<rootDir>/src/explore/$1",
    "^@/reels/(.*)$": "<rootDir>/src/reels/$1",
    "^@/profile/(.*)$": "<rootDir>/src/profile/$1",
    "^@/calls/(.*)$": "<rootDir>/src/calls/$1",
    "^@/secondary/(.*)$": "<rootDir>/src/secondary/$1",
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|@react-native|@react-native-community|@react-navigation|expo|expo-modules-core|expo-.*|@expo|@expo/vector-icons|@unimodules|unimodules|react-navigation|@react-native-async-storage|@react-native-picker|lodash)/',
  ],
  collectCoverage: true,
  coverageDirectory: "coverage",
  coverageReporters: ["text", "json", "html", "lcov"],
  coverageThreshold: {
    global: {
      branches: 75,
      functions: 70,
      lines: 80,
      statements: 80,
    },
    "./src/feed/feed.mapper.ts": {
      branches: 75,
      functions: 90,
      lines: 85,
      statements: 85,
    },
    "./src/chat/message.mapper.ts": {
      branches: 50,
      functions: 90,
      lines: 90,
      statements: 90,
    },
    "./src/chat/chat.mapper.ts": {
      branches: 80,
      functions: 100,
      lines: 80,
      statements: 80,
    },
    "./src/chat/chat.api.ts": {
      branches: 80,
      functions: 100,
      lines: 80,
      statements: 80,
    },
    "./src/chat/message.api.ts": {
      branches: 80,
      functions: 100,
      lines: 80,
      statements: 80,
    },
    "./src/auth/auth.api.ts": {
      branches: 80,
      functions: 100,
      lines: 80,
      statements: 80,
    },
    // Former FeedRepositoryAdapter body (not the thin FeedUseCases passthrough)
    "./src/feed/feed.api.ts": {
      branches: 75,
      functions: 85,
      lines: 90,
      statements: 90,
    },
  },
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/**/*.d.ts",
    "!src/**/__tests__/**",
    "!src/**/__mocks__/**",
    "!src/app/**",
    "!src/feed/home-feed-screen.tsx",
    "!src/explore/explore-screen.tsx",
    "!src/reels/reels-screen.tsx",
    "!src/profile/profile-screen.tsx",
    "!src/secondary/settings-menu-screen.tsx",
    "!src/feed/feedApi.ts",
    "!src/core/store/**",
    "!src/core/composition-root.ts",
    "!src/core/call/**",
    "!src/core/rtc/**",
    "!src/calls/**",
    "!src/layout/**",
    "!src/shared/components/ActiveCallOverlay.tsx",
    "!src/shared/components/CallOverlay.tsx",
    "!src/shared/components/IncomingCallOverlay.tsx",
  ],
};
